/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import Connection.CallJar;
import Connection.Client;
import filetrackingapp.FileTrackingApp;
import filetrackingapp.ThreadGenerator;
import java.io.File;
import java.io.IOException;
import java.net.UnknownHostException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Neel_Esh
 */
public class FileChooseFrame extends javax.swing.JFrame {

    /**
     * Creates new form FileChooseFrame
     */
    private File file;
    private String Email;
    public FileChooseFrame()
    {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public FileChooseFrame(String email) {
        initComponents();
        this.Email=email;
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        FilePathTxt = new javax.swing.JTextField();
        StrtOperationBtn = new javax.swing.JButton();
        BrowseFileBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(192, 205, 240));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Select File or Directory :-");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        FilePathTxt.setEditable(false);
        FilePathTxt.setBackground(new java.awt.Color(211, 194, 236));
        FilePathTxt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        FilePathTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        FilePathTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilePathTxtActionPerformed(evt);
            }
        });
        jPanel1.add(FilePathTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 421, 25));

        StrtOperationBtn.setBackground(new java.awt.Color(211, 194, 236));
        StrtOperationBtn.setText("Start Operation on this file");
        StrtOperationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StrtOperationBtnActionPerformed(evt);
            }
        });
        jPanel1.add(StrtOperationBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, -1, -1));

        BrowseFileBtn.setBackground(new java.awt.Color(211, 194, 236));
        BrowseFileBtn.setText("Browse File");
        BrowseFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseFileBtnActionPerformed(evt);
            }
        });
        jPanel1.add(BrowseFileBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 110, -1));

        BackBtn.setBackground(new java.awt.Color(211, 194, 236));
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        jPanel1.add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 152, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("/Users/Neel_Esh/Desktop/Screenshot 2022-06-14 at 00.27.06.png")); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BrowseFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowseFileBtnActionPerformed
       
        JFileChooser chooser=new JFileChooser();
        
        chooser.setDialogTitle("Browse Files");
        chooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        
        int result =chooser.showOpenDialog(null);
        
        if (result == chooser.APPROVE_OPTION) 
        {   
            file=chooser.getSelectedFile();
            System.out.println(file.toString());
            FilePathTxt.setText(file.toString().trim());
        } 
        else if (result == chooser.CANCEL_OPTION) 
        {
            System.out.println("Cancel was selected");
        }
    }//GEN-LAST:event_BrowseFileBtnActionPerformed

    private void StrtOperationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StrtOperationBtnActionPerformed
        // TODO add your handling code here:
        if(FilePathTxt.getText().trim().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Select File First !!!","Error",JOptionPane.WARNING_MESSAGE);
        }
        else
        {
          //FileTrackingApp.startTracking(file);
          ThreadGenerator th=new ThreadGenerator(Email,file);
          System.out.println("Started");
          //CallJar.startTracking(Email, file.toString().trim());
//            try
//            {   
//                
//                Client.setConnection("127.0.0.1",1210);
//                Client.startClientSide(Email, file);
////              ThreadGenerator th=new ThreadGenerator(Email,file);
//                System.out.println("Started");
//            }
//            catch(UnknownHostException u)
//            {
//		System.out.println(u);
//                u.printStackTrace();
//            }
//            catch(IOException i)
//            {
//		System.out.println(i);
//                i.printStackTrace();
//            }
            
        }
    }//GEN-LAST:event_StrtOperationBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
//         TODO add your handling code here:
        UserOptionFrame userFrame=new UserOptionFrame(Email);
        userFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackBtnActionPerformed

    private void FilePathTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilePathTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FilePathTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FileChooseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FileChooseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FileChooseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FileChooseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FileChooseFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton BrowseFileBtn;
    private javax.swing.JTextField FilePathTxt;
    private javax.swing.JButton StrtOperationBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
